server:
  port: 9010
spring:
  application:
    name: mss-eureka
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
eureka:
  instance:
    hostname: mss-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
  #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false